### ISSUE TITLE
StoryMap _ Map1

### ISSUE THREAD

**Issue by Jewel4575** [slu-soc5650/module-4-storymap-1#2]
**Building out the StoryMap**
In Lab 4-1, you created a map showing the location of Missouri in
1830 as well as a map showing the state and territory populations
as of the 1830 Decennial Census. Add both of these to your map
document under a new heading with a paragraph of placeholder
text. You should use either the Slideshow or Sidecar tool for adding
these maps. This entire section of content should be located under
the “Comparing Changes” section we created during class

https://arcg.is/zj9W4 @chris-prener

**Comment by Jewel4575** [comment]
# @chris-prener

**Comment by chris-prener** [comment]
This needs to be submitted via your assignments repository, @Jewel4575. Thanks!
